driver:
  name: docker
  use_sudo: false
provisioner:
  name: chef_zero
verifier:
  name: inspec
platforms:
- name: centos-6.6
- name: ubuntu-14.04
suites:
- name: default
  run_list:
  - recipe[HMMER::default]
  attributes:
