name 'HMMER'
maintainer 'The Authors'
maintainer_email 'chef@eaglegenomics.com'
license 'all_rights'
description 'Installs/Configures HMMER'
long_description 'Installs/Configures HMMER'
version '1.0.0'

depends 'build-essential'
depends 'magic_shell'
